(function(_){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
var ba,fa,ka,la,pa,qa,va,wa,Aa,Da,D,Ta,Ua,Va,Xa,bb,kb,lb,ob,qb,rb,sb,ub,Cb,Db,Ib,Kb,Jb,Nb,Pb,Qb,Rb,Sb,Tb,Vb,Ub,Wb,Yb,Xb,$b,ac,bc,ec,fc,jc,mc,pc,sc,tc,uc,wc,xc,yc,Ac,Bc,Ec,Fc,Dc,Cc,vc,Gc,Hc,Jc,Nc,Pc,Qc,Rc,Tc,Uc,Yc,Wc,Zc,cd,ed,dd,gd,hd,id,ld,od,rd,sd,ud,vd,wd,yd,ha,zd,ia,Ed,Fd;ba=function(a){return function(){return _.aa[a].apply(this,arguments)}};_.da=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}; 
_.ea=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:_.da(a)}};fa=function(a){if(!(a instanceof Array)){a=_.ea(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a};ka=function(a,b){a.prototype=ha(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.R=b.prototype}; 
la=function(a){a=["object"==typeof globalThis&&globalThis,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global,a];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};pa=function(a,b){if(b){var c=_.na;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&(0,_.oa)(c,a,{configurable:!0,writable:!0,value:b})}}; 
qa=function(a,b){this.b=a;(0,_.oa)(this,"description",{configurable:!0,writable:!0,value:b})};_.q=function(a,b,c){a=a.split(".");c=c||_.p;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};_.ra=function(){}; 
_.sa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null"; 
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.ta=function(a){return"function"==_.sa(a)};_.ua=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};va=function(a,b,c){return a.call.apply(a.bind,arguments)}; 
wa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}};_.u=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?_.u=va:_.u=wa;return _.u.apply(null,arguments)}; 
_.v=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}};_.y=function(a,b){function c(){}c.prototype=b.prototype;a.R=b.prototype;a.prototype=new c;a.prototype.constructor=a};_.ya=function(a,b){b=(0,_.xa)(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c};_.za=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}; 
Aa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};Da=function(a,b){this.g=a===Ba&&b||"";this.h=Ca};_.Ea=function(a){return a instanceof Da&&a.constructor===Da&&a.h===Ca?a.g:"type_error:Const"};_.z=function(a){return new Da(Ba,a)};_.A=function(a,b){this.h=a===_.Fa&&b||"";this.j=Ga};_.Ha=function(a){if(a instanceof _.A&&a.constructor===_.A&&a.j===Ga)return a.h;_.sa(a);return"type_error:TrustedResourceUrl"};_.B=function(a,b){this.h=a===_.Ia&&b||"";this.j=Ja}; 
_.Ka=function(a){if(a instanceof _.B&&a.constructor===_.B&&a.j===Ja)return a.h;_.sa(a);return"type_error:SafeUrl"};_.Ma=function(a){if(a instanceof _.B)return a;a="object"==typeof a&&a.T?a.b():String(a);La.test(a)||(a="about:invalid#zClosurez");return new _.B(_.Ia,a)};D=function(a){return-1!=Na.indexOf(a)};_.Pa=function(){this.h="";this.l=Oa;this.j=null};_.Qa=function(a){if(a instanceof _.Pa&&a.constructor===_.Pa&&a.l===Oa)return a.h;_.sa(a);return"type_error:SafeHtml"}; 
_.Ra=function(a,b){var c=new _.Pa;c.h=a;c.j=b;return c};Ta=function(a){var b=new _.A(_.Fa,_.Ea(Sa));a.src=_.Ha(b).toString()};Ua=function(){return D("iPhone")&&!D("iPod")&&!D("iPad")};Va=function(a){Va[" "](a);return a};_.Wa=function(a,b){try{return Va(a[b]),!0}catch(c){}return!1};Xa=function(){var a=_.p.document;return a?a.documentMode:void 0};_.E=function(){}; 
_.G=function(a,b,c){a.b=null;b||(b=[]);a.w=void 0;a.j=-1;a.g=b;a:{if(b=a.g.length){--b;var d=a.g[b];if(!(null===d||"object"!=typeof d||Array.isArray(d)||Ya&&d instanceof Uint8Array)){a.l=b-a.j;a.h=d;break a}}a.l=Number.MAX_VALUE}a.v={};if(c)for(b=0;b<c.length;b++)if(d=c[b],d<a.l)d+=a.j,a.g[d]=a.g[d]||Za;else{var e=a.l+a.j;a.g[e]||(a.h=a.g[e]={});a.h[d]=a.h[d]||Za}};_.$a=function(a,b){if(b<a.l){b+=a.j;var c=a.g[b];return c===Za?a.g[b]=[]:c}if(a.h)return c=a.h[b],c===Za?a.h[b]=[]:c}; 
_.H=function(a,b,c){a=_.$a(a,b);return null==a?c:a};_.I=function(a,b){a=_.$a(a,b);a=null==a?a:!!a;return null==a?!1:a};_.ab=function(a,b,c){a.b||(a.b={});if(!a.b[c]){var d=_.$a(a,c);d&&(a.b[c]=new b(d))}return a.b[c]};bb=function(a,b,c){a.b||(a.b={});if(!a.b[c]){for(var d=_.$a(a,c),e=[],f=0;f<d.length;f++)e[f]=new b(d[f]);a.b[c]=e}b=a.b[c];b==Za&&(b=a.b[c]=[]);return b};_.cb=function(a){if(a.b)for(var b in a.b){var c=a.b[b];if("array"==_.sa(c))for(var d=0;d<c.length;d++)c[d]&&_.cb(c[d]);else c&&_.cb(c)}return a.g}; 
_.fb=function(a){_.G(this,a,db)};_.gb=function(a){return _.H(a,22,"")};_.ib=function(a){return _.H(a,23,"")};kb=function(a){_.G(this,a,null)};lb=function(a){_.G(this,a,null)};_.nb=function(a){_.G(this,a,null)};ob=function(a){_.G(this,a,null)};qb=function(a){_.G(this,a,pb)};rb=function(a){return bb(a,_.fb,1)};_.J=function(a,b,c){a.addEventListener&&a.addEventListener(b,c,!1)};sb=function(a,b){this.b=void 0!==a?a:0;this.g=void 0!==b?b:0}; 
_.tb=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)};_.vb=function(a,b,c){ub(a,b,void 0===c?null:c)};ub=function(a,b,c){a.google_image_requests||(a.google_image_requests=[]);var d=a.document.createElement("img");if(c){var e=function(f){c&&c(f);d.removeEventListener&&d.removeEventListener("load",e,!1);d.removeEventListener&&d.removeEventListener("error",e,!1)};_.J(d,"load",e);_.J(d,"error",e)}d.src=b;a.google_image_requests.push(d)}; 
_.wb=function(a){var b=a.indexOf("#");0>b&&(b=a.length);var c=a.indexOf("?");if(0>c||c>b){c=b;var d=""}else d=a.substring(c+1,b);return[a.substr(0,c),d,a.substr(b)]};_.xb=function(a,b){return b?a?a+"&"+b:b:a};_.yb=function(a,b){if(!b)return a;a=_.wb(a);a[1]=_.xb(a[1],b);return a[0]+(a[1]?"?"+a[1]:"")+a[2]};_.zb=function(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)_.zb(a,String(b[d]),c);else null!=b&&c.push(a+(""===b?"":"="+encodeURIComponent(String(b))))}; 
_.Ab=function(a){var b=[],c;for(c in a)_.zb(c,a[c],b);return b.join("&")};_.Bb=function(a,b){b=_.Ab(b);return _.yb(a,b)};Cb=function(a){try{return!!a&&null!=a.location.href&&_.Wa(a,"foo")}catch(b){return!1}};Db=function(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(void 0,a[c],c,a)};_.Eb=function(a){a.preventDefault?a.preventDefault():a.returnValue=!1}; 
Ib=function(a,b){var c=_.Fb(599);b=b instanceof _.B||!Gb.test(b)?b:new _.B(_.Ia,b);_.Hb(b,c);c=b instanceof _.B?b:_.Ma(b);a.href=_.Ka(c)};_.Hb=function(a,b){"about:invalid#zClosurez"===(a instanceof _.B?a:_.Ma(a)).b()&&b(String(a))};_.Fb=function(a){var b=(Jb()?"http:":"https:")+"//pagead2.googlesyndication.com/pagead/gen_204";return function(c){c=_.Bb(b,{id:"unsafeurl",ctx:a,url:c});navigator.sendBeacon&&navigator.sendBeacon(c,"")}}; 
Kb=function(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(void 0,a[c],c,a)};Jb=function(){var a=void 0===a?_.K:a;return"http:"===a.location.protocol};_.Mb=function(a,b,c){c=void 0===c?_.Lb:c;switch(a){case 2:return c.getElementsByClassName(b);case 3:return c.getElementsByTagName(b)}return[]};_.L=function(a,b,c){c=void 0===c?_.Lb:c;switch(a){case 1:if(c.getElementById)return c.getElementById(b);break;case 2:case 3:if(a=_.Mb(a,b,c),0<a.length)return a[0]}return null}; 
Nb=function(a,b){a&&Kb(b,function(c,d){a.style[d]=c})};_.Ob=function(a){a=_.ea(a);for(var b=a.next();!b.done;b=a.next())if(b=b.value,"use_refactored_boomerang_click_handler"===_.H(b,1,"")&&"true"===_.H(b,2,"").toLowerCase())return!0;return!1};Pb=function(a,b){var c=void 0===c?{}:c;this.error=a;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror";this.meta=c};Qb=function(a,b){this.b=a;this.g=b};Rb=function(a,b){this.url=a;this.Ia=!!b;this.depth=null}; 
Sb=function(){this.h="&";this.j=!1;this.g={};this.l=0;this.b=[]};Tb=function(a,b){var c={};c[a]=b;return[c]};Vb=function(a,b,c,d,e){var f=[];Db(a,function(g,h){(g=Ub(g,b,c,d,e))&&f.push(h+"="+g)});return f.join(b)}; 
Ub=function(a,b,c,d,e){if(null==a)return"";b=b||"&";c=c||",$";"string"==typeof c&&(c=c.split(""));if(a instanceof Array){if(d=d||0,d<c.length){for(var f=[],g=0;g<a.length;g++)f.push(Ub(a[g],b,c,d+1,e));return f.join(c[d])}}else if("object"==typeof a)return e=e||0,2>e?encodeURIComponent(Vb(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))};Wb=function(a,b,c,d){a.b.push(b);a.g[b]=Tb(c,d)}; 
Yb=function(a,b,c){b=b+"//pagead2.googlesyndication.com"+c;var d=Xb(a)-c.length;if(0>d)return"";a.b.sort(function(n,r){return n-r});c=null;for(var e="",f=0;f<a.b.length;f++)for(var g=a.b[f],h=a.g[g],m=0;m<h.length;m++){if(!d){c=null==c?g:c;break}var l=Vb(h[m],a.h,",$");if(l){l=e+l;if(d>=l.length){d-=l.length;b+=l;e=a.h;break}a.j&&(e=d,l[e-1]==a.h&&--e,b+=l.substr(0,e),e=a.h,d=0);c=null==c?g:c}}a="";null!=c&&(a=e+"trn="+c);return b+a}; 
Xb=function(a){var b=1,c;for(c in a.g)b=c.length>b?c.length:b;return 3997-b-a.h.length-1};_.Zb=function(a,b,c,d,e,f){if((d?a.b:Math.random())<(e||.01))try{if(c instanceof Sb)var g=c;else g=new Sb,Db(c,function(m,l){var n=g,r=n.l++;m=Tb(l,m);n.b.push(r);n.g[r]=m});var h=Yb(g,a.g,"/pagead/gen_204?id="+b+"&");h&&("undefined"===typeof f?_.vb(_.p,h):_.vb(_.p,h,f))}catch(m){}};$b=function(){var a=_.p.performance;return a&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):(0,_.M)()}; 
ac=function(){var a=void 0===a?_.p:a;return(a=a.performance)&&a.now?a.now():null};bc=function(a,b,c){this.label=a;this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.slotId=void 0};ec=function(){var a=cc;this.events=[];this.g=a||_.p;var b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.events=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.b=dc()||(null!=b?b:1>Math.random())}; 
fc=function(a){a&&N&&dc()&&(N.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_start"),N.clearMarks("goog_"+a.label+"_"+a.uniqueId+"_end"))};_.ic=function(){var a=gc;this.j=_.hc;this.g=null;this.v=this.h;this.b=void 0===a?null:a;this.l=!1};_.kc=function(a,b,c){try{if(a.b&&a.b.b){var d=a.b.start(b.toString(),3);var e=c();a.b.end(d)}else e=c()}catch(f){c=!0;try{fc(d),c=a.v(b,new Pb(f,{message:jc(f)}),void 0,void 0)}catch(g){a.h(217,g)}if(!c)throw f;}return e}; 
jc=function(a){var b=a.toString();a.name&&-1==b.indexOf(a.name)&&(b+=": "+a.name);a.message&&-1==b.indexOf(a.message)&&(b+=": "+a.message);if(a.stack){a=a.stack;try{-1==a.indexOf(b)&&(a=b+"\n"+a);for(var c;a!=c;)c=a,a=a.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");b=a.replace(/\n */g,"\n")}catch(d){}}return b};mc=function(){if(!cc.google_measure_js_timing){var a=gc;a.b=!1;a.events!=a.g.google_js_reporting_queue&&(dc()&&(0,_.lc)(a.events,fc),a.events.length=0)}}; 
_.nc=function(a,b){if(!a||/[?&]dsh=1(&|$)/.test(a))return null;if(/[?&]ae=1(&|$)/.test(a)){var c=/[?&]adurl=([^&]+)/.exec(a);if(!c)return null;b=b?c.index:a.length;try{return{oa:a.slice(0,b)+"&act=1"+a.slice(b),G:decodeURIComponent(c[1])}}catch(e){return null}}if(/[?&]ae=2(&|$)/.test(a)){c=a;var d="";b&&(b=a.indexOf("&adurl="),0<b&&(c=a.slice(0,b),d=a.slice(b)));return{oa:c+"&act=1"+d,G:c+"&dct=1"+d}}return null};pc=function(a){var b=_.oc(a.href),c=b.ba;Ib(a,b.V);return c}; 
_.oc=function(a){var b=_.nc(a,!0);return b?navigator.sendBeacon?navigator.sendBeacon(_.qc(b.oa,"&ri=1"),"")?{V:b.G,ba:!0}:{V:_.qc(a,"&ri=2"),ba:!1}:{V:_.qc(a,"&ri=16"),ba:!1}:{V:a,ba:!1}};_.qc=function(a,b){var c=a.search(/&adurl=/);return 0>c?a+b:a.slice(0,c)+b+a.slice(c)};_.rc=function(a){return null!=a&&-1===a.indexOf("dbm/clk")&&null!==_.nc(a)};sc=function(a){return _.rc(a.href)||(a.getAttribute("data-orig-async-clicktrack-url")?_.rc(a.getAttribute("data-orig-async-clicktrack-url")):!1)}; 
tc=function(a,b,c,d,e){c="&"+b+"="+c;var f=a.indexOf("&"+d+"=");c=0>f?a+c:a.substring(0,f)+c+a.substring(f);return 2E3<c.length?void 0!==e?tc(a,b,e,d,void 0):a:c};uc=function(a,b,c,d){b=c(d,b);if(!(b instanceof Array))return a;(0,_.lc)(b,function(e){if(2!==e.length&&3!==e.length)return a;a=tc(a,e[0],e[1],"adurl",e[2])});return a}; 
wc=function(a,b,c){this.b=a;this.j=b;this.h=c;this.F=[];this.l=[];this.O={};this.g={};this.A=this.B=!1;this.w=vc(this.b);this.I=new Promise(function(d){d(!1)});this.v=-1;a=_.gb(this.b);b=_.ib(this.b);c=bb(this.j,lb,23);this.h&&this.b&&a&&b&&_.Ob(c)&&2===vc(this.b)&&(this.w=2,this.I=this.h.Ta({url:a,id:a,D:b}))};xc=function(a,b,c){var d=b=b.getAttribute("data-original-click-url");if(d)for(var e=0;e<a.F.length;e++)d=uc(d,b,a.F[e],c);return d}; 
yc=function(a,b){b=void 0===b?Date.now():b;return b-a.v>_.H(a.b,39,0)};Ac=function(a,b){-1===b.href.indexOf("dbm/clk")&&(sc(b)||_.I(a.b,38))&&_.kc(_.zc,446,function(){var c=Date.now(),d;if(d=yc(a,c)){d=_.I(a.b,45);var e=a.v;d?300>Date.now()-(void 0===e?-1:e)?d=!1:(d=b.getAttribute("data-orig-async-clicktrack-url"))?(d=_.oc(d),e=d.ba,Ib(b,d.V),d=e):(b.setAttribute("data-orig-async-clicktrack-url",b.href),d=pc(b)):d=pc(b)}d&&(a.v=c)})}; 
Bc=function(a,b,c,d){if(0!=a.l.length&&(d.preventDefault?!d.defaultPrevented:!1!==d.returnValue)){var e=1==d.which&&!d.ctrlKey&&"_blank"!=b.target&&"_new"!=b.target;e&&_.Eb(d);for(var f=[],g={},h=0;h<a.l.length;g={ga:g.ga},h++)if(g.ga=a.l[h](c),g.ga){var m=new Promise(function(l){return function(n){_.vb(_.K,l.ga,n)}}(g));f.push(m)}c=Promise.all(f);f=new Promise(function(l){window.setTimeout(l,2E3)});e&&Promise.race([c,f]).then((0,_.u)(wc.prototype.aa,a,b,d))}}; 
Ec=function(a,b,c){var d=bb(a.j,lb,23),e=!1;d=_.ea(d);for(var f=d.next();!f.done;f=d.next())if(f=f.value,"use_async_for_js_click_handler"===_.H(f,1,"")&&"True"===_.H(f,2,"")){e=!0;break}e&&a.h&&2===a.w?(_.Eb(c),Cc(a,b,c,a.w,a.I).then(function(g){g||Ac(a,b)})):Dc(a,b,c)||Ac(a,b)};Fc=function(a,b,c,d){a.g[d]||(a.g[d]={});a.g[d][c]||(a.g[d][c]=[]);_.J(b,d,(0,_.u)(a.$,a,b,c,d))}; 
Dc=function(a,b,c){var d=b.href;if(a.h){var e=Date.now(),f=yc(a,e);if(a.h.Ha(b,c,a.b,a.A,f))return f&&(a.v=e),!0}else if(_.p.googdlu&&(_.p.googdlu.tryOpenPlayStore&&_.p.googdlu.tryOpenPlayStore(c,d,_.H(a.b,15,""))||_.p.googdlu.tryOpenItunesStore&&_.p.googdlu.tryOpenItunesStore(c,d,_.H(a.b,15,""),_.I(a.b,42),_.I(a.b,43),_.H(a.j,7,""),_.H(a.j,8,""))))return!0;return _.I(a.b,31)&&_.I(a.b,30)&&_.H(a.b,28,"")&&_.p.googdlu&&_.p.googdlu.tryOpenAppUrl?(_.p.googdlu.tryOpenAppUrl(c,d,_.H(a.b,32,""),_.H(a.b, 
28,"")),!0):!1};Cc=function(a,b,c,d,e){if(a.h){var f=yc(a,Date.now()),g=bb(a.j,lb,23);return a.h.Za(b,c,a.b,a.A,e,f,g,d)}return new Promise(function(h){h(!1)})};vc=function(a){return _.I(a,31)&&_.H(a,28,"")?1:_.gb(a)&&_.ib(a)?_.I(a,44)?3:2:0};Gc=function(a){return"string"==typeof a.className?a.className:a.getAttribute&&a.getAttribute("class")||""};Hc=function(a,b){"string"==typeof a.className?a.className=b:a.setAttribute&&a.setAttribute("class",b)}; 
Jc=function(a,b){a.classList?b=a.classList.contains(b):(a=a.classList?a.classList:Gc(a).match(/\S+/g)||[],b=0<=(0,_.xa)(a,b));return b};_.Kc=function(a,b){if(a.classList)a.classList.add(b);else if(!Jc(a,b)){var c=Gc(a);Hc(a,c+(0<c.length?" "+b:b))}};_.Mc=function(a,b){a.classList?a.classList.remove(b):Jc(a,b)&&Hc(a,Lc(a.classList?a.classList:Gc(a).match(/\S+/g)||[],function(c){return c!=b}).join(" "))};Nc=function(a){_.p.setTimeout(function(){throw a;},0)}; 
Pc=function(){var a=_.p.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!D("Presto")&&(a=function(){var e=_.tb(document,"IFRAME");e.style.display="none";Ta(e);document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.write(_.Qa(Oc));e.close();var g="callImmediate"+Math.random(),h="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;e=(0,_.u)(function(m){if(("*"==h||m.origin==h)&&m.data== 
g)this.port1.onmessage()},this);f.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(g,h)}}});if("undefined"!==typeof a&&!D("Trident")&&!D("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(void 0!==c.next){c=c.next;var e=c.Ca;c.Ca=null;e()}};return function(e){d.next={Ca:e};d=d.next;b.port2.postMessage(0)}}return function(e){_.p.setTimeout(e,0)}};Qc=function(a,b){this.h=a;this.j=b;this.g=0;this.b=null};Rc=function(){this.g=this.b=null}; 
Tc=function(){var a=Sc,b=null;a.b&&(b=a.b,a.b=a.b.next,a.b||(a.g=null),b.next=null);return b};Uc=function(){this.next=this.g=this.b=null};Yc=function(a){Vc||Wc();Xc||(Vc(),Xc=!0);Sc.add(a,void 0)};Wc=function(){if(_.p.Promise&&_.p.Promise.resolve){var a=_.p.Promise.resolve(void 0);Vc=function(){a.then(Zc)}}else Vc=function(){var b=Zc;!_.ta(_.p.setImmediate)||_.p.Window&&_.p.Window.prototype&&!D("Edge")&&_.p.Window.prototype.setImmediate==_.p.setImmediate?($c||($c=Pc()),$c(b)):_.p.setImmediate(b)}}; 
Zc=function(){for(var a;a=Tc();){try{a.b.call(a.g)}catch(c){Nc(c)}var b=ad;b.j(a);100>b.g&&(b.g++,a.next=b.b,b.b=a)}Xc=!1};_.O=function(){this.j=this.j;this.h=this.h};_.bd=function(a){_.O.call(this);this.w=1;this.l=[];this.v=0;this.b=[];this.g={};this.B=!!a};cd=function(a,b,c){Yc(function(){a.apply(b,c)})}; 
ed=function(a,b,c,d,e){this.v=new _.bd;this.g=a;this.g[0]=[b];this.j=[];this.h=new wc(c,d,e);this.l=d;this.b=c;b=_.gb(this.b);c=_.ib(this.b);d=bb(this.l,lb,23);if(d=e&&this.b&&_.Ob(d))d=this.b,d=2===(_.I(d,31)&&_.H(d,28,"")?1:_.gb(d)&&_.ib(d)?_.I(d,44)?3:2:0);!d&&b&&c&&e&&(e.canOpenIntents([{url:b,id:b,D:c}],(0,_.u)(this.La,this))||e.canOpenURLs(b,(0,_.u)(this.La,this)));(e=_.L(1,"common_15click_anchor"))?(a[20]=[e],dd(this,20)):(e=_.za(_.Mb(2,"common_15click_anchor")),0<e.length&&(a[20]=e,dd(this, 
20)))};_.fd=function(a,b,c){a=a.getElementsByAdPiece(b);if(c)for(b=0;b<a.length;b++){var d=a[b].getAttribute(c);if(d)return d}return null};dd=function(a,b){if((null==_.$a(a.l,28)||!_.I(_.ab(a.l,kb,28),12))&&a.g[b]&&a.la(b)){a.j.push(b);var c=a.h;a=a.g[b];for(var d=0;d<a.length;d++){var e=a[d],f=e;f.href&&f.setAttribute("data-original-click-url",f.href);Fc(c,e,b,"mousedown");Fc(c,e,b,"click")}c.O[b]=!0}};gd=function(a,b){a=a.getElementsByAdPiece(b);for(b=0;b<a.length;b++)if(!a[b].href)return!1;return!0}; 
hd=function(a){this.w=new _.bd;this.l=null;this.h=[];this.b=a;this.j=[];this.v=!1;this.g=null};id=function(a){var b=[a];b=void 0===b?[]:b;_.p.google_logging_queue||(_.p.google_logging_queue=[]);_.p.google_logging_queue.push([10,b]);a=new hd(new qb(a));return window.adSlot=a};_.jd=function(){var a=window.adSlot;return a?a:(_.zc.h(536,Error("no adslot"),void 0,void 0),id(null))};ld=function(a,b,c){ed.call(this,a,b,c,_.jd().b,_.jd().g);for(a=0;a<kd.length;a++)dd(this,kd[a])}; 
od=function(a,b){var c=md,d={};if(!b)return null;d[0]=[b];Kb(nd,function(e){c[e]&&(d[e]=_.za(_.Mb(2,c[e],b)))});return new ld(d,b,a)};rd=function(a,b,c){b.gqid=pd;b.qqid=qd;b.com=a;_.Zb(_.hc,"glaurung",b,!0,c,void 0)};sd=function(a,b){var c=_.ab(b,ob,16);c&&_.I(c,12)&&_.I(b,5)&&Nb(a,{backgroundColor:"transparent",backgroundImage:"none"})}; 
ud=function(a,b,c){_.L(2,"app-icon-link",b)&&(md[33]="app-icon-link");var d=a.b,e=_.L(1,"adunit",b),f=_.L(1,"ads",b);if(!e||!f)return 1;var g={overflow:"hidden"};0==_.H(d,32,0)?(g.width=_.H(d,2,0)+"px",g.height=_.H(d,3,0)+"px",g.position="absolute",g.top="0",g.left="0"):(g.width="100%",g.height="100%");Nb(e,g);sd(e,d);sd(f,d);try{c(f,a)}catch(l){return _.I(d,13)&&(td=l),2}c=0;d=rb(d);for(e=0;e<d.length;e++){g=d[e];var h="taw"+_.H(g,2,0);f=_.L(1,h,b);if(!f)return 3;f=od(g,f);if(!f)return 1;var m=_.K.registerAd; 
m?m(f,h):c=4;_.I(g,11)&&_.K.initAppPromo&&_.K.initAppPromo(f,a);if(_.I(g,19)&&(g=_.$a(g,33),0<g.length))for(h=0;h<g.length;h++)m=(0,_.u)(ld.prototype.w,f,g[h]),f.h.l.push(m);a.na(f)}return c};vd=function(a,b,c){var d=[];d[0]=[c];d[15]=[b];(b=_.L(1,"abgc"))&&(d[27]=[b]);(b=_.L(1,"cbc"))&&(d[28]=[b]);(b=_.L(1,"cta-button-anchor"))&&(d[4]=[b]);ed.call(this,d,c,a,_.jd().b,_.jd().g);dd(this,15);b&&dd(this,4)};wd=function(a,b){var c={};c[0]=[b];ed.call(this,c,b,a,_.jd().b,_.jd().g)}; 
yd=function(a,b,c){ed.call(this,a,b,c,_.jd().b,_.jd().g);for(a=0;a<xd.length;a++)dd(this,xd[a]);this.listen(4,"mouseover",(0,_.u)(this.C,this,0,"onhoverbg",!1));this.listen(4,"mouseout",(0,_.u)(this.C,this,0,"onhoverbg",!0))};_.aa=[];ha="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b}; 
if("function"==typeof Object.setPrototypeOf)zd=Object.setPrototypeOf;else{var Ad;a:{var Bd={Sa:!0},Cd={};try{Cd.__proto__=Bd;Ad=Cd.Sa;break a}catch(a){}Ad=!1}zd=Ad?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}ia=zd;_.na=la(this);_.oa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)}; 
pa("Promise",function(a){function b(g){this.g=0;this.h=void 0;this.b=[];var h=this.j();try{g(h.resolve,h.reject)}catch(m){h.reject(m)}}function c(){this.b=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.g=function(g){if(null==this.b){this.b=[];var h=this;this.h(function(){h.l()})}this.b.push(g)};var e=_.na.setTimeout;c.prototype.h=function(g){e(g,0)};c.prototype.l=function(){for(;this.b&&this.b.length;){var g=this.b;this.b=[];for(var h=0;h<g.length;++h){var m= 
g[h];g[h]=null;try{m()}catch(l){this.j(l)}}}this.b=null};c.prototype.j=function(g){this.h(function(){throw g;})};b.prototype.j=function(){function g(l){return function(n){m||(m=!0,l.call(h,n))}}var h=this,m=!1;return{resolve:g(this.F),reject:g(this.l)}};b.prototype.F=function(g){if(g===this)this.l(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.I(g);else{a:switch(typeof g){case "object":var h=null!=g;break a;case "function":h=!0;break a;default:h=!1}h?this.B(g):this.v(g)}}; 
b.prototype.B=function(g){var h=void 0;try{h=g.then}catch(m){this.l(m);return}"function"==typeof h?this.O(h,g):this.v(g)};b.prototype.l=function(g){this.w(2,g)};b.prototype.v=function(g){this.w(1,g)};b.prototype.w=function(g,h){if(0!=this.g)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.g);this.g=g;this.h=h;this.A()};b.prototype.A=function(){if(null!=this.b){for(var g=0;g<this.b.length;++g)f.g(this.b[g]);this.b=null}};var f=new c;b.prototype.I=function(g){var h=this.j(); 
g.ia(h.resolve,h.reject)};b.prototype.O=function(g,h){var m=this.j();try{g.call(h,m.resolve,m.reject)}catch(l){m.reject(l)}};b.prototype.then=function(g,h){function m(t,F){return"function"==typeof t?function(C){try{l(t(C))}catch(w){n(w)}}:F}var l,n,r=new b(function(t,F){l=t;n=F});this.ia(m(g,l),m(h,n));return r};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.ia=function(g,h){function m(){switch(l.g){case 1:g(l.h);break;case 2:h(l.h);break;default:throw Error("Unexpected state: "+ 
l.g);}}var l=this;null==this.b?f.g(m):this.b.push(m)};b.resolve=d;b.reject=function(g){return new b(function(h,m){m(g)})};b.race=function(g){return new b(function(h,m){for(var l=_.ea(g),n=l.next();!n.done;n=l.next())d(n.value).ia(h,m)})};b.all=function(g){var h=_.ea(g),m=h.next();return m.done?d([]):new b(function(l,n){function r(C){return function(w){t[C]=w;F--;0==F&&l(t)}}var t=[],F=0;do t.push(void 0),F++,d(m.value).ia(r(t.length-1),n),m=h.next();while(!m.done)})};return b}); 
qa.prototype.toString=function(){return this.b};_.Dd=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new qa("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();_.p=this||self;Ed="closure_uid_"+(1E9*Math.random()>>>0);Fd=0;_.M=Date.now||function(){return+new Date};var Lc;_.xa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.lc=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e="string"===typeof a?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)}; 
Lc=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f="string"===typeof a?a.split(""):a,g=0;g<c;g++)if(g in f){var h=f[g];b.call(void 0,h,g,a)&&(d[e++]=h)}return d};_.Gd=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};Da.prototype.T=!0;Da.prototype.b=function(){return this.g};var Ca={},Ba={},Sa=_.z("");var Ga;_.A.prototype.T=!0;_.A.prototype.b=function(){return this.h.toString()};_.A.prototype.sa=!0;_.A.prototype.g=ba(2);Ga={};_.Fa={};_.Hd=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var La,Ja;_.B.prototype.T=!0;_.B.prototype.b=function(){return this.h.toString()};_.B.prototype.sa=!0;_.B.prototype.g=ba(1);La=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;Ja={};_.Ia={};var Na;a:{var Id=_.p.navigator;if(Id){var Jd=Id.userAgent;if(Jd){Na=Jd;break a}}Na=""};_.Pa.prototype.sa=!0;_.Pa.prototype.g=ba(0);_.Pa.prototype.T=!0;_.Pa.prototype.b=function(){return this.h.toString()};var Oa={};_.Ra("<!DOCTYPE html>",0);var Oc=_.Ra("",0);_.Ra("<br>",0);_.Kd=Aa(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=_.Qa(Oc);return!b.parentElement});Va[" "]=_.ra;var Nd,Td,Yd;_.Ld=D("Opera");_.Md=D("Trident")||D("MSIE");Nd=D("Edge");_.Od=D("Gecko")&&!(-1!=Na.toLowerCase().indexOf("webkit")&&!D("Edge"))&&!(D("Trident")||D("MSIE"))&&!D("Edge");_.Pd=-1!=Na.toLowerCase().indexOf("webkit")&&!D("Edge");_.Qd=D("Android");_.Rd=Ua();_.Sd=D("iPad"); 
a:{var Ud="",Vd=function(){var a=Na;if(_.Od)return/rv:([^\);]+)(\)|;)/.exec(a);if(Nd)return/Edge\/([\d\.]+)/.exec(a);if(_.Md)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Pd)return/WebKit\/(\S+)/.exec(a);if(_.Ld)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Vd&&(Ud=Vd?Vd[1]:"");if(_.Md){var Wd=Xa();if(null!=Wd&&Wd>parseFloat(Ud)){Td=String(Wd);break a}}Td=Ud}_.Xd=Td;if(_.p.document&&_.Md){var Zd=Xa();Yd=Zd?Zd:parseInt(_.Xd,10)||void 0}else Yd=void 0;_.$d=Yd;_.ae=Ua()||D("iPod");_.be=D("iPad");_.ce=D("Android")&&!((D("Chrome")||D("CriOS"))&&!D("Edge")||D("Firefox")||D("FxiOS")||D("Opera")||D("Silk"));var Ya="function"==typeof Uint8Array,Za=[];_.y(_.fb,_.E);var db=[20,33];_.y(kb,_.E);_.y(lb,_.E);_.y(_.nb,_.E);_.y(ob,_.E);_.y(qb,_.E);var pb=[1,23];var nd;nd={yb:0,Yb:1,Zb:45,$b:46,Mb:48,URL:2,rb:3,ib:4,Xb:5,Rb:7,Eb:8,pb:9,Gb:6,Jb:34,zb:13,jb:14,Fb:15,Hb:16,Ib:40,Vb:47,cc:29,vb:30,Wb:49,Nb:17,sb:18,xb:19,wb:20,Tb:23,nb:24,Qb:25,Pb:26,ob:27,Ob:28,bc:39,ac:31,ub:32,lb:33,Ab:35,Kb:36,kb:37,tb:38,Lb:42,Sb:43,Ub:44,qb:50,Bb:1E3,Cb:1001,Db:1002};_.de=[16,47,49,18,27,28,39];sb.prototype.ceil=function(){this.b=Math.ceil(this.b);this.g=Math.ceil(this.g);return this};sb.prototype.floor=function(){this.b=Math.floor(this.b);this.g=Math.floor(this.g);return this};sb.prototype.round=function(){this.b=Math.round(this.b);this.g=Math.round(this.g);return this};_.P=0;_.Lb=document;_.K=window;var Gb=/^((market|itms|intent|itms-appss):\/\/)/i;var ee=!!window.google_async_iframe_id,fe=ee&&window.parent||window;_.Ea(_.z("//fonts.googleapis.com/css"));var ge=/^https?:\/\/(\w|-)+\.cdn\.ampproject\.(net|org)(\?|\/|$)/;var he=null;var N=_.p.performance,ie=!!(N&&N.mark&&N.measure&&N.clearMarks),dc=Aa(function(){var a;if(a=ie){var b;if(null===he){he="";try{a="";try{a=_.p.top.location.hash}catch(c){a=_.p.location.hash}a&&(he=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=he;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});ec.prototype.start=function(a,b){if(!this.b)return null;var c=ac()||$b();a=new bc(a,b,c);b="goog_"+a.label+"_"+a.uniqueId+"_start";N&&dc()&&N.mark(b);return a}; 
ec.prototype.end=function(a){if(this.b&&"number"===typeof a.value){var b=ac()||$b();a.duration=b-a.value;b="goog_"+a.label+"_"+a.uniqueId+"_end";N&&dc()&&N.mark(b);!this.b||2048<this.events.length||this.events.push(a)}};_.ic.prototype.pinger=ba(3); 
_.ic.prototype.h=function(a,b,c,d,e){e=e||"jserror";try{var f=new Sb;f.j=!0;Wb(f,1,"context",a);b.error&&b.meta&&b.id||(b=new Pb(b,{message:jc(b)}));b.msg&&Wb(f,2,"msg",b.msg.substring(0,512));var g=b.meta||{};if(this.g)try{this.g(g)}catch(x){}if(d)try{d(g)}catch(x){}b=[g];f.b.push(3);f.g[3]=b;d=_.p;b=[];g=null;do{var h=d;if(Cb(h)){var m=h.location.href;g=h.document&&h.document.referrer||null}else m=g,g=null;b.push(new Rb(m||""));try{d=h.parent}catch(x){d=null}}while(d&&h!=d);m=0;for(var l=b.length- 
1;m<=l;++m)b[m].depth=l-m;h=_.p;if(h.location&&h.location.ancestorOrigins&&h.location.ancestorOrigins.length==b.length-1)for(l=1;l<b.length;++l){var n=b[l];n.url||(n.url=h.location.ancestorOrigins[l-1]||"",n.Ia=!0)}var r=new Rb(_.p.location.href,!1);h=null;var t=b.length-1;for(n=t;0<=n;--n){var F=b[n];!h&&ge.test(F.url)&&(h=F);if(F.url&&!F.Ia){r=F;break}}F=null;var C=b.length&&b[t].url;0!=r.depth&&C&&(F=b[t]);var w=new Qb(r,F);w.g&&Wb(f,4,"top",w.g.url||"");Wb(f,5,"url",w.b.url||"");_.Zb(this.j,e, 
f,this.l,c)}catch(x){try{_.Zb(this.j,e,{context:"ecmserr",rctx:a,msg:jc(x),url:w&&w.b.url},this.l,c)}catch(eb){}}return!0};if(ee&&!Cb(fe)){var je="."+_.Lb.domain;try{for(;2<je.split(".").length&&!Cb(fe);)_.Lb.domain=je=je.substr(je.indexOf(".")+1),fe=window.parent}catch(a){}Cb(fe)||(fe=window)}var cc=fe,gc=new ec;_.hc=new function(){this.g=Jb()?"http:":"https:";this.b=Math.random()};"number"!==typeof cc.google_srt&&(cc.google_srt=Math.random());var ke=_.hc,le=cc.google_srt;0<=le&&1>=le&&(ke.b=le);_.zc=new _.ic; 
_.zc.g=function(a){var b=_.K.jerExpIds;if("array"==_.sa(b)&&0!==b.length){var c=a.eid;if(c){b=fa(c.split(",")).concat(fa(b));c={};for(var d=0,e=0;e<b.length;){var f=b[e++];var g=f;g=_.ua(g)?"o"+(Object.prototype.hasOwnProperty.call(g,Ed)&&g[Ed]||(g[Ed]=++Fd)):(typeof g).charAt(0)+g;Object.prototype.hasOwnProperty.call(c,g)||(c[g]=!0,b[d++]=f)}b.length=d;a.eid=b.join(",")}else a.eid=b.join(",")}0!==_.P&&(a.jc=String(_.P));(b=_.K.jerUserAgent)&&(a.useragent=b)};_.zc.l=!0; 
"complete"==cc.document.readyState?mc():gc.b&&_.J(cc,"load",function(){mc()});wc.prototype.aa=function(a,b){this.B=!0;var c=!1;if(b.target){c=b.target;var d=b.button,e=b.ctrlKey,f=b.shiftKey,g=b.metaKey,h=b.altKey,m=new sb(b.x,b.y);if(document.createEvent){var l=document.createEvent("MouseEvents");l.initMouseEvent("click",!0,!0,null,0,m.b,m.g,m.b,m.g,e,h,f,g,d,null);c.dispatchEvent?(c.dispatchEvent(l),c=!0):c=!1}else c=!1}!a.href||c||Dc(this,a,b)||(Ac(this,a),_.K.top.location=a.href)}; 
wc.prototype.$=function(a,b,c,d){if(this.B)this.B=!1;else{d||(d=_.K.event);this.g[c][b].forEach(function(f){f(d)});if(a.href){var e=xc(this,a,d.type);e&&(a.href=e)}"click"==c&&(Bc(this,a,b,d),(d.preventDefault?d.defaultPrevented:!1===d.returnValue)||Ec(this,a,d))}};var $c;Qc.prototype.get=function(){if(0<this.g){this.g--;var a=this.b;this.b=a.next;a.next=null}else a=this.h();return a};var ad=new Qc(function(){return new Uc},function(a){a.reset()});Rc.prototype.add=function(a,b){var c=ad.get();c.set(a,b);this.g?this.g.next=c:this.b=c;this.g=c};Uc.prototype.set=function(a,b){this.b=a;this.g=b;this.next=null};Uc.prototype.reset=function(){this.next=this.g=this.b=null};var Vc,Xc=!1,Sc=new Rc;_.O.prototype.j=!1;_.O.prototype.pa=ba(4);_.O.prototype.H=ba(6);_.y(_.bd,_.O);_.bd.prototype.subscribe=function(a,b,c){var d=this.g[a];d||(d=this.g[a]=[]);var e=this.w;this.b[e]=a;this.b[e+1]=b;this.b[e+2]=c;this.w=e+3;d.push(e);return e};_.bd.prototype.F=function(a){var b=this.b[a];b&&(b=this.g[b],0!=this.v?(this.l.push(a),this.b[a+1]=_.ra):(b&&_.ya(b,a),delete this.b[a],delete this.b[a+1],delete this.b[a+2]))}; 
_.bd.prototype.A=function(a,b){var c=this.g[a];if(c){for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];if(this.B)for(e=0;e<c.length;e++){var g=c[e];cd(this.b[g+1],this.b[g+2],d)}else{this.v++;try{for(e=0,f=c.length;e<f;e++)g=c[e],this.b[g+1].apply(this.b[g+2],d)}finally{if(this.v--,0<this.l.length&&0==this.v)for(;c=this.l.pop();)this.F(c)}}}};_.bd.prototype.H=ba(5);_.k=ed.prototype;_.k.La=function(a,b){b=(a=_.gb(this.b))&&b?b[a]:!1;this.h.A=!!b;this.C(0,"app_installed",!b);this.C(0,"rh-ani",b)};_.k.navigationAdPieces=function(){return this.j};_.k.la=function(){return!0};_.k.has=function(a){return(a=this.g[a])&&0<a.length};_.k.listen=function(a,b,c){var d=this.g[a];if(d){var e=this.h;c=_.v(c,a,this);var f=("click"==b||"mousedown"==b)&&e.O[a];e.g[b]||(e.g[b]={});e.g[b][a]||(e.g[b][a]=[]);e.g[b][a].push(c);if(!f)for(a=0;a<d.length;a++)_.J(d[a],b,c)}}; 
_.k.C=function(a,b,c){if(b){a=this.getElementsByAdPiece(a);for(var d=0;d<a.length;d++)c?_.Mc(a[d],b):_.Kc(a[d],b)}};_.k.getElementsByAdPiece=function(a){return this.g[a]?this.g[a]:[]};_.k.creativeConversionUrl=function(){return _.H(this.b,6,"")};_.k.redirectUrl=function(){return _.H(this.b,8,"")};_.k.getIndex=function(){return _.H(this.b,2,0)};_.k.listenOnObject=function(a,b){this.v.subscribe(a,b)};_.k.fireOnObject=function(a,b){this.v.A(a,b)};_.k=hd.prototype;_.k.forEachAd=function(a){(0,_.lc)(this.h,a)};_.k.na=function(a){this.h.push(a)};_.k.Xa=function(a){if(a=_.L(1,a))this.l=a;if(0==this.h.length)_.p.css=null;else{for(a=0;a<this.j.length;++a)this.j[a]();this.v=!0}};_.k.listenOnObject=function(a,b){this.w.subscribe(a,b)};_.k.fireOnObject=function(a,b){this.w.A(a,b)};_.k.registerFinalizeCallback=function(a){this.v?a():this.j.push(a)};_.k.getSerializedAdSlotData=function(){return _.cb(this.b)};_.k.getAdsLength=function(){return this.h.length}; 
_.k.getAd=function(a){return 0<=a&&a<this.h.length&&this.h[a].getIndex()==a?this.h[a]:null};_.k.getContainer=function(){return this.l};_.k.openSystemBrowser=function(a){return this.g?(this.g.openSystemBrowser(a,{useFirstPackage:!0,useRunningProcess:!0}),!0):!1};_.k.openAttribution=function(a){return this.g?(this.g.openSystemBrowser(a,{useFirstPackage:!0,useRunningProcess:!0,useCustomTabs:!0}),!0):!1};ka(ld,ed);ld.prototype.la=function(a){return gd(this,a)||4===a};ld.prototype.w=function(a,b){return this.la(b)?a:""};var kd=[1,2,3,4,8,6,40,33,36,37,38,9];var pd="UNKNOWN",qd="UNKNOWN",td=null,Q={},md=(Q[1]="title-link",Q[2]="url-link",Q[3]="body-link",Q[4]="button-link",Q[8]="favicon-link",Q[6]="image-link",Q[26]="price",Q[23]="reviews",Q[43]="rating-stars",Q[44]="reviews-count",Q[24]="app-store",Q[25]="promo-headline",Q[33]="app-icon",Q[16]="image-gallery",Q[40]="image-gallery-image-link",Q[36]="logo-link",Q[37]="advertiser-link",Q[38]="call-to-action-link",Q[39]="video",Q[42]="logo",Q[50]="badge-box",Q[9]="ad-background",Q);ka(vd,ed);ka(wd,ed);ka(yd,ed);yd.prototype.la=function(a){return gd(this,a)||4==a}; 
var S={},me=(S[1]="rhtitle",S[45]="rhtitleline1",S[46]="rhtitleline2",S[48]="rhlongtitle",S[3]="rhbody",S[2]="rhurl",S[4]="rhbutton",S[8]="rhfavicon",S[14]="rhaddress",S[6]="rhimage",S[34]="rhimagetemplate",S[49]="rh-scrollflow",S[16]="rhimagegallery",S[47]="rhreviewgallery",S[29]="rhviewimagegallery",S[30]="rhcloseimagegalleryview",S[31]="rhtrydemobutton",S[32]="rhclosetrydemoview",S[39]="rhvideo",S[9]="rhbackground",S[13]="rh-icore-empty",S[5]="rhsitelink",S[7]="rhradlink",S[17]="rh-multiframe", 
S[18]="rh-box-breadcrumbs",S[23]="rhstarratings",S[24]="rhstoreicon",S[25]="rhpromotext",S[26]="rhprice",S[27]="abgc",S[28]="cbc",S[35]="rhdemocountdowntimer",S[36]="rhlogo",S[1001]="rhoverlap-imagegallery",S[1002]="rhoverlap-trydemo",S),xd=[1,45,46,48,2,4,5,7,8,3,9,6,14,15,34,26,24,36];_.P=5;hd.prototype.forEachAd=hd.prototype.forEachAd;hd.prototype.addAd=hd.prototype.na;hd.prototype.finalize=hd.prototype.Xa;_.q("buildAdSlot",id,void 0);_.q("buildGlaurungAds",function(a,b,c){var d=(new Date).getTime(),e=1,f=!1;td=null;try{var g=a.b;f=_.I(g,13);pd=_.H(g,8,"");qd=_.H(g,7,"");e=ud(a,b,c)}catch(h){f&&(td=h),e=1}a={};rd("bridge",(a.r=e,a.d=(new Date).getTime()-d,a));return e},void 0);_.q("glaurungError",function(){return td},void 0);_.q("glaurungBridge.log",rd,void 0); 
_.q("glaurungBridge.getAdPieceClassName",function(a){return md[a]},void 0);_.q("buildImageAd",function(a,b){if(0>b||b>=rb(a.b).length)a=null;else{a=rb(a.b)[b];b=_.L(1,"google_image_div");var c=_.L(1,"aw0");a=b&&c?new vd(a,c,b):null}return a},void 0);_.q("buildRichmediaAd",function(a,b){return 0>b||b>=rb(a.b).length?null:new wd(rb(a.b)[b],_.Lb.body)},void 0); 
_.q("buildTextAd",function(a,b){var c=a.b;if(!(0>b||b>=rb(c).length)){if(0>b||b>=rb(a.b).length)var d=null;else{d=rb(a.b)[b];var e=_.L(1,"taw"+b);if(e){var f={0:[e]},g;for(g in nd){var h=nd[g],m=me[h];m&&(f[h]=_.za(_.Mb(2,m,e)))}d=new yd(f,e,d)}else d=null}d&&(_.K.registerAd&&_.K.registerAd(d,"taw"+b),a.na(d),_.I(rb(c)[b],11)&&_.K.initAppPromo&&_.K.initAppPromo(d,a))}},void 0);})(window.hydra=window.hydra||{});
